platform2.orbit8.com/openstack-dashboard/openstack_dashboard/dashboards/admin/volumes/urls.py
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url

from openstack_dashboard.dashboards.admin.volumes.snapshots \
    import urls as snapshot_urls
from openstack_dashboard.dashboards.admin.volumes import views
from openstack_dashboard.dashboards.admin.volumes.volume_types \
    import urls as volume_types_urls
from openstack_dashboard.dashboards.admin.volumes.volumes \
    import urls as volumes_urls

urlpatterns = patterns(
    '',
    url(r'^$',
        views.IndexView.as_view(),
        name='index'),
    url(r'^\?tab=volumes_group_tabs__snapshots_tab$',
        views.IndexView.as_view(),
        name='snapshots_tab'),
    url(r'^\?tab=volumes_group_tabs__volumes_tab$',
        views.IndexView.as_view(),
        name='volumes_tab'),
    url(r'^\?tab=volumes_group_tabs__volume_types_tab$',
        views.IndexView.as_view(),
        name='volume_types_tab'),
    url(r'',
        include(volumes_urls, namespace='volumes')),
    url(r'volume_types/',
        include(volume_types_urls, namespace='volume_types')),
    url(r'snapshots/',
        include(snapshot_urls, namespace='snapshots')),
)

platform2.orbit8.com/openstack-dashboard/openstack_dashboard/dashboards/admin/volumes/volumes/urls.py
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

from django.conf.urls import patterns
from django.conf.urls import url

from openstack_dashboard.dashboards.admin.volumes.volumes \
    import views

VIEWS_MOD = ('openstack_dashboard.dashboards.admin.volumes.volumes.views')

urlpatterns = patterns(
    VIEWS_MOD,
    url(r'^manage/$',
        views.ManageVolumeView.as_view(),
        name='manage'),
    url(r'^(?P<volume_id>[^/]+)/$',
        views.DetailView.as_view(),
        name='detail'),
    url(r'^(?P<volume_id>[^/]+)/update_status$',
        views.UpdateStatusView.as_view(),
        name='update_status'),
    url(r'^(?P<volume_id>[^/]+)/unmanage$',
        views.UnmanageVolumeView.as_view(),
        name='unmanage'),
    url(r'^(?P<volume_id>[^/]+)/migrate$',
        views.MigrateVolumeView.as_view(),
        name='migrate'),
)

platform2.orbit8.com/openstack-dashboard/openstack_dashboard/dashboards/project/volumes/urls.py
# Copyright 2012 Nebula, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url

from openstack_dashboard.dashboards.project.volumes.backups \
    import urls as backups_urls
from openstack_dashboard.dashboards.project.volumes.cgroups \
    import urls as cgroup_urls
from openstack_dashboard.dashboards.project.volumes.snapshots \
    import urls as snapshot_urls
from openstack_dashboard.dashboards.project.volumes import views
from openstack_dashboard.dashboards.project.volumes.volumes \
    import urls as volume_urls

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^\?tab=volumes_and_snapshots__snapshots_tab$',
        views.IndexView.as_view(), name='snapshots_tab'),
    url(r'^\?tab=volumes_and_snapshots__volumes_tab$',
        views.IndexView.as_view(), name='volumes_tab'),
    url(r'^\?tab=volumes_and_snapshots__backups_tab$',
        views.IndexView.as_view(), name='backups_tab'),
    url(r'^\?tab=volumes_and_snapshots__cgroups_tab$',
        views.IndexView.as_view(), name='cgroups_tab'),
    url(r'', include(volume_urls, namespace='volumes')),
    url(r'backups/', include(backups_urls, namespace='backups')),
    url(r'snapshots/', include(snapshot_urls, namespace='snapshots')),
    url(r'cgroups/', include(cgroup_urls, namespace='cgroups')),
)

platform2.orbit8.com/openstack-dashboard/openstack_dashboard/urls.py
# Copyright 2012 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
# Copyright 2012 Nebula, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""
URL patterns for the OpenStack Dashboard.
"""

from django.conf import settings
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls.static import static  # noqa
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns  # noqa

import horizon

urlpatterns = patterns(
    '',
    url(r'^$', 'openstack_dashboard.views.splash', name='splash'),
    url(r'^api/', include('openstack_dashboard.api.rest.urls')),
    url(r'', include(horizon.urls)),
)

for u in getattr(settings, 'AUTHENTICATION_URLS', ['openstack_auth.urls']):
    urlpatterns += patterns(
        '',
        url(r'^auth/', include(u))
    )

# Development static app and project media serving using the staticfiles app.
urlpatterns += staticfiles_urlpatterns()

# Convenience function for serving user-uploaded media during
# development. Only active if DEBUG==True and the URL prefix is a local
# path. Production media should NOT be served by Django.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^500/$', 'django.views.defaults.server_error')
    )

platform2.orbit8.com/openstack-dashboard/openstack_dashboard/dashboards/project/volumes/volumes/forms.py
# Copyright 2012 Nebula, Inc.
# All rights reserved.

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

"""
Views for managing volumes.
"""

from django.conf import settings
from django.core.urlresolvers import reverse
from django.forms import ValidationError  # noqa
from django import http
from django.template.defaultfilters import filesizeformat  # noqa
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _

from horizon import exceptions
from horizon import forms
from horizon import messages
from horizon.utils import functions
from horizon.utils.memoized import memoized  # noqa

from openstack_dashboard import api
from openstack_dashboard.api import cinder
from openstack_dashboard.api import glance
from openstack_dashboard.api import nova
from openstack_dashboard.dashboards.project.images import utils
from openstack_dashboard.dashboards.project.instances import tables
from openstack_dashboard.usage import quotas

IMAGE_BACKEND_SETTINGS = getattr(settings, 'OPENSTACK_IMAGE_BACKEND', {})
IMAGE_FORMAT_CHOICES = IMAGE_BACKEND_SETTINGS.get('image_formats', [])
VALID_DISK_FORMATS = ('raw', 'vmdk', 'vdi', 'qcow2')
DEFAULT_CONTAINER_FORMAT = 'bare'


# Determine whether the extension for Cinder AZs is enabled
def cinder_az_supported(request):
    try:
        return cinder.extension_supported(request, 'AvailabilityZones')
    except Exception:
        exceptions.handle(request, _('Unable to determine if availability '
                                     'zones extension is supported.'))
        return False


def availability_zones(request):
    zone_list = []
    if cinder_az_supported(request):
        try:
            zones = api.cinder.availability_zone_list(request)
            zone_list = [(zone.zoneName, zone.zoneName)
                         for zone in zones if zone.zoneState['available']]
            zone_list.sort()
        except Exception:
            exceptions.handle(request, _('Unable to retrieve availability '
                                         'zones.'))
    if not zone_list:
        zone_list.insert(0, ("", _("No availability zones found")))
    elif len(zone_list) > 1:
        zone_list.insert(0, ("", _("Any Availability Zone")))

    return zone_list


class CreateForm(forms.SelfHandlingForm):
    name = forms.CharField(max_length=255, label=_("Volume Name"),
                           required=False)
    description = forms.CharField(max_length=255, widget=forms.Textarea(
        attrs={'rows': 4}),
        label=_("Description"), required=False)
    volume_source_type = forms.ChoiceField(label=_("Volume Source"),
                                           required=False,
                                           widget=forms.Select(attrs={
                                               'class': 'switchable',
                                               'data-slug': 'source'}))
    snapshot_source = forms.ChoiceField(
        label=_("Use snapshot as a source"),
        widget=forms.SelectWidget(
            attrs={'class': 'snapshot-selector'},
            data_attrs=('size', 'name'),
            transform=lambda x: "%s (%s GiB)" % (x.name, x.size)),
        required=False)
    image_source = forms.ChoiceField(
        label=_("Use image as a source"),
        widget=forms.SelectWidget(
            attrs={'class': 'image-selector'},
            data_attrs=('size', 'name', 'min_disk'),
            transform=lambda x: "%s (%s)" % (x.name, filesizeformat(x.bytes))),
        required=False)
    volume_source = forms.ChoiceField(
        label=_("Use a volume as source"),
        widget=forms.SelectWidget(
            attrs={'class': 'image-selector'},
            data_attrs=('size', 'name'),
            transform=lambda x: "%s (%s GiB)" % (x.name, x.size)),
        required=False)
    type = forms.ChoiceField(
        label=_("Type"),
        required=False,
        widget=forms.Select(
            attrs={'class': 'switched',
                   'data-switch-on': 'source',
                   'data-source-no_source_type': _('Type'),
                   'data-source-image_source': _('Type')}))
    size = forms.IntegerField(min_value=1, initial=1, label=_("Size (GiB)"))
    availability_zone = forms.ChoiceField(
        label=_("Availability Zone"),
        required=False,
        widget=forms.Select(
            attrs={'class': 'switched',
                   'data-switch-on': 'source',
                   'data-source-no_source_type': _('Availability Zone'),
                   'data-source-image_source': _('Availability Zone')}))

    def prepare_source_fields_if_snapshot_specified(self, request):
        try:
            snapshot = self.get_snapshot(request,
                                         request.GET["snapshot_id"])
            self.fields['name'].initial = snapshot.name
            self.fields['size'].initial = snapshot.size
            self.fields['snapshot_source'].choices = ((snapshot.id,
                                                       snapshot),)
            try:
                # Set the volume type from the original volume
                orig_volume = cinder.volume_get(request,
                                                snapshot.volume_id)
                self.fields['type'].initial = orig_volume.volume_type
            except Exception:
                pass
            self.fields['size'].help_text = (
                _('Volume size must be equal to or greater than the '
                  'snapshot size (%sGiB)') % snapshot.size)
            del self.fields['image_source']
            del self.fields['volume_source']
            del self.fields['volume_source_type']
            del self.fields['availability_zone']
        except Exception:
            exceptions.handle(request,
                              _('Unable to load the specified snapshot.'))

    def prepare_source_fields_if_image_specified(self, request):
        self.fields['availability_zone'].choices = \
            availability_zones(request)
        try:
            image = self.get_image(request,
                                   request.GET["image_id"])
            image.bytes = image.size
            self.fields['name'].initial = image.name
            min_vol_size = functions.bytes_to_gigabytes(
                image.size)
            size_help_text = (_('Volume size must be equal to or greater '
                                'than the image size (%s)')
                              % filesizeformat(image.size))
            properties = getattr(image, 'properties', {})
            min_disk_size = (getattr(image, 'min_disk', 0) or
                             properties.get('min_disk', 0))
            if (min_disk_size > min_vol_size):
                min_vol_size = min_disk_size
                size_help_text = (_('Volume size must be equal to or '
                                    'greater than the image minimum '
                                    'disk size (%sGiB)')
                                  % min_disk_size)
            self.fields['size'].initial = min_vol_size
            self.fields['size'].help_text = size_help_text
            self.fields['image_source'].choices = ((image.id, image),)
            del self.fields['snapshot_source']
            del self.fields['volume_source']
            del self.fields['volume_source_type']
        except Exception:
            msg = _('Unable to load the specified image. %s')
            exceptions.handle(request, msg % request.GET['image_id'])

    def prepare_source_fields_if_volume_specified(self, request):
        self.fields['availability_zone'].choices = \
            availability_zones(request)
        volume = None
        try:
            volume = self.get_volume(request, request.GET["volume_id"])
        except Exception:
            msg = _('Unable to load the specified volume. %s')
            exceptions.handle(request, msg % request.GET['volume_id'])

        if volume is not None:
            self.fields['name'].initial = volume.name
            self.fields['description'].initial = volume.description
            min_vol_size = volume.size
            size_help_text = (_('Volume size must be equal to or greater '
                                'than the origin volume size (%sGiB)')
                              % volume.size)
            self.fields['size'].initial = min_vol_size
            self.fields['size'].help_text = size_help_text
            self.fields['volume_source'].choices = ((volume.id, volume),)
            self.fields['type'].initial = volume.type
            del self.fields['snapshot_source']
            del self.fields['image_source']
            del self.fields['volume_source_type']

    def prepare_source_fields_default(self, request):
        source_type_choices = []
        self.fields['availability_zone'].choices = \
            availability_zones(request)

        try:
            available = api.cinder.VOLUME_STATE_AVAILABLE
            snapshots = cinder.volume_snapshot_list(
                request, search_opts=dict(status=available))
            if snapshots:
                source_type_choices.append(("snapshot_source",
                                            _("Snapshot")))
                choices = [('', _("Choose a snapshot"))] + \
                          [(s.id, s) for s in snapshots]
                self.fields['snapshot_source'].choices = choices
            else:
                del self.fields['snapshot_source']
        except Exception:

platform2.orbit8.com/openstack-dashboard/openstack_dashboard/dashboards/project/volumes/templates/volumes/volumes/_attach.html
{% extends "horizon/common/_modal_form.html" %}
{% load i18n %}

{% block modal-body %}
  {% if show_attach %}
    <h3>{% trans "Attach To Instance" %}</h3>
    <fieldset>
      {% include "horizon/common/_form_fields.html" %}
    </fieldset>
  {% endif %}
{% endblock %}

{% block modal-footer %}
    <a href="{% url 'horizon:project:volumes:index' %}" class="btn btn-default cancel">{% trans "Cancel" %}</a>
  {% if show_attach %}
    <input class="btn btn-primary" type="submit" value="{% trans "Attach Volume" %}" />
  {% endif %}
{% endblock %}

platform2.orbit8.com/openstack-dashboard/openstack_dashboard/dashboards/project/volumes/templates/volumes/volumes/_create_snapshot.html
{% extends "horizon/common/_modal_form.html" %}
{% load i18n %}

{% block modal-body-right %}
  <div class="quota-dynamic">
    {% include "project/volumes/volumes/_snapshot_limits.html" with usages=usages snapshot_quota=True %}
  </div>
{% endblock %}

{% block modal-footer %}
  <a href="{% url 'horizon:project:volumes:index' %}" class="btn btn-default cancel">{% trans "Cancel" %}</a>
  {% if attached %}
    <input class="btn btn-warning" type="submit" value="{% trans "Create Volume Snapshot (Force)" %}" />
  {% else %}
    <input class="btn btn-primary" type="submit" value="{% trans "Create Volume Snapshot" %}" />
  {% endif %}
{% endblock %}

platform2.orbit8.com/openstack-dashboard/openstack_dashboard/dashboards/project/volumes/templates/volumes/volumes/_create_transfer.html
{% extends "horizon/common/_modal_form.html" %}
{% load i18n %}

{% block modal-body-right %}
    <h3>{% trans "Description:" %}</h3>
    <p>{% trans 'Ownership of a volume can be transferred from one project to another. Once a volume transfer is created in a donor project, it then can be "accepted" by a recipient project. This is equivalent to the <tt>cinder transfer-create</tt> command.' %}</p>
{% endblock %}

platform2.orbit8.com/openstack-dashboard/openstack_dashboard/dashboards/project/volumes/templates/volumes/volumes/_detail_overview.html
{% load i18n sizeformat parse_date %}

<div class="detail">
  <dl class="dl-horizontal">
    <dt>{% trans "Name" %}</dt>
    <dd>{{ volume.name }}</dd>
    <dt>{% trans "ID" %}</dt>
    <dd>{{ volume.id }}</dd>
    {% if volume.description %}
    <dt>{% trans "Description" %}</dt>
    <dd>{{ volume.description }}</dd>
    {% endif %}
    <dt>{% trans "Status" %}</dt>
    <dd>{{ volume.status_label|capfirst }}</dd>
  </dl>

  <h4>{% trans "Specs" %}</h4>
  <hr class="header_rule">
  <dl class="dl-horizontal">
    <dt>{% trans "Size" %}</dt>
    <dd>{{ volume.size }} {% trans "GiB" %}</dd>
    {% if volume.volume_type %}
    <dt>{% trans "Type" %}</dt>
    <dd>{{ volume.volume_type }}</dd>
    {% endif %}
    {% if volume.availabilty_zone %}
    <dt>{% trans "Availability zone" %}</dt>
    <dd>{{ volume.availability_zone }}</dd>
    {% endif %}
    <dt>{% trans "Bootable" %}</dt>
    <dd>{{ volume.is_bootable|yesno|capfirst }}</dd>
    <dt>{% trans "Encrypted" %}</dt>
    <dd><a href="{% url 'horizon:project:volumes:volumes:encryption_detail' volume.id %}">{{ volume.encrypted|yesno:_("yes,no,-")|capfirst }}</a></dd>
    <dt>{% trans "Created" context "Created time" %}</dt>
    <dd>{{ volume.created_at|parse_date }}</dd>
  </dl>

  <h4>{% trans "Attachments" %}</h4>
  <hr class="header_rule">
  <dl class="dl-horizontal">
  {% for attachment in volume.attachments %}
    <dt>{% trans "Attached To" %}</dt>
    <dd>
      {% url 'horizon:project:instances:detail' attachment.server_id as instance_url %}
      {% blocktrans with instance_name=attachment.instance.name device=attachment.device %}
      <a href="{{ instance_url }}">{{ instance_name }}</a> on {{ device }}
      {% endblocktrans %}
    </dd>
  {% empty %}
    <dt>{% trans "Attached To" %}</dt>
    <dd><em>{% trans "Not attached" %}</em></dd>
  {% endfor %}
  </dl>

{% if volume.volume_image_metadata %}
  <h4>{% trans "Volume Source" %}</h4>
  <hr class="header_rule">
  <dl class="dl-horizontal">
    <dt>{% trans "Image" %}</dt>
    <dd>
      {% url 'horizon:project:images:images:detail' volume.volume_image_metadata.image_id as image_url %}
      <a href="{{ image_url }}">{{ volume.volume_image_metadata.image_name }}</a>
    </dd>
  </dl>
{% endif %}

  <h4>{% trans "Metadata" %}</h4>
  <hr class="header_rule">
  <dl class="dl-horizontal">
  {% if volume.metadata.items %}
      {% for key, value in volume.metadata.items %}
          <dt>{{ key }}</dt>
          <dd>{{ value }}</dd>
      {% endfor %}
  {% else %}
      <dd>{% trans "None" %}</dd>
  {% endif %}
  </dl>

{% if volume.transfer %}
  <h4>{% trans "Volume Transfer" %}</h4>
  <hr class="header_rule">
  <dl>
      <dt>{% trans "ID" %}</dt>
      <dd>{{ volume.transfer.id }}</dd>
  </dl>
  <dl>
      <dt>{% trans "Name" %}</dt>
      <dd>{{ volume.transfer.name }}</dd>
  </dl>
  <dl>
      <dt>{% trans "Created" context "Created time" %}</dt>
      <dd>{{ volume.transfer.created_at|parse_date }}</dd>
  </dl>
{% endif %}
</div>

platform2.orbit8.com/openstack-dashboard/openstack_dashboard/dashboards/project/volumes/templates/volumes/volumes/_encryption_detail_overview.html
{% load i18n %}

{% if encryption_metadata.provider %}
<h3>{% trans "Volume Encryption Overview" %}</h3>

<div class="info row detail">
  <div class="col-sm-12">
    <h4>{% trans "Info" %}</h4>
    <hr class="header_rule">
    <dl class="dl-horizontal">
      <dt>{% trans "Volume Type Name" %}</dt>
      <dd>{{ volume.volume_type }}</dd>
      <dt>{% trans "Provider" %}</dt>
      <dd>{{ encryption_metadata.provider }}</dd>
      <dt>{% trans "Control Location" %}</dt>
      <dd>{{ encryption_metadata.control_location }}</dd>
      <dt>{% trans "Cipher" %}</dt>
      <dd>{{ encryption_metadata.cipher }}</dd>
      <dt>{% trans "Key Size (bits)" %}</dt>
      <dd>{{ encryption_metadata.key_size }}</dd>
    </dl>
  </div>
</div>
{% else %}
<h3>{% trans "Volume is Unencrypted" %}</h3>
{% endif %}

platform2.orbit8.com/openstack-dashboard/openstack_dashboard/dashboards/project/volumes/templates/volumes/volumes/_limits.html
{% load i18n horizon humanize bootstrap %}

<h3>{% trans "Description:" %}</h3>

<p>{% blocktrans %}Volumes are block devices that can be attached to instances.{% endblocktrans %}</p>

<div id="id_show_volume_type_desc_div">
  <h3>{% trans "Volume Type Description:" %}</h3>
  <h4>
    <strong id="id_show_volume_type_name"></strong>
  </h4>
  <p id="id_show_volume_type_desc"></p>
</div>

<h3>{% block head %}{% trans "Volume Limits" %}{% endblock %}</h3>

<div class="quota_title">
  <div class="pull-left">
    <strong">{% trans "Total Gibibytes" %}</strong>
    <span>({% block gigabytes_used %}{{ usages.gigabytesUsed|intcomma }}{% endblock %} {% trans "GiB" %})</span>
  </div>
  <span class="pull-right">{{ usages.maxTotalVolumeGigabytes|intcomma|quota:_("GiB") }}</span>
</div>

{{ minifyspace }}
<div id="quota_size"
     data-progress-indicator-for="id_size"
     data-quota-limit="{{ usages.maxTotalVolumeGigabytes }}"
     data-quota-used={% block gigabytes_used_progress %}"{{ usages.gigabytesUsed }}"{% endblock %}
     class="quota_bar">
  {% widthratio usages.gigabytesUsed usages.maxTotalVolumeGigabytes 100 as gigabytes_percent %}
  {% bs_progress_bar gigabytes_percent 0 %}
</div>
{{ endminifyspace }}

<div class="quota_title">
  <div class="pull-left">
    <strong>{% block type_title %}{% trans "Number of Volumes" %}{% endblock %}</strong>
    <span>({% block used %}{{ usages.volumesUsed|intcomma }}{% endblock %})</span>
  </div>
  <span class="pull-right">{% block total %}{{ usages.maxTotalVolumes|intcomma|quota }}{% endblock %}</span>
</div>

{{ minifyspace }}
<div id={% block type_id %}"quota_volumes"{% endblock %}
     data-quota-limit={% block total_progress %}"{{ usages.maxTotalVolumes }}"{% endblock %}
     data-quota-used={% block used_progress %}"{{ usages.volumesUsed }}"{% endblock %}
     class="quota_bar">
  {% widthratio usages.volumesUsed usages.maxTotalVolumes 100 as volumes_percent %}
  {% widthratio 100 usages.maxTotalVolumes 1 as single_step %}
  {% bs_progress_bar volumes_percent single_step %}
</div>
{{ endminifyspace }}

<script type="text/javascript" charset="utf-8">
  if(typeof horizon.Quota !== 'undefined') {
    horizon.Quota.init();
  } else {
    addHorizonLoadEvent(function() {
      horizon.Quota.init();
    });
  }

  if(typeof horizon.Volumes !== 'undefined') {
    horizon.Volumes.initWithTypes({{ volume_types|safe|default:"{}" }});
  } else {
    addHorizonLoadEvent(function() {
      horizon.Volumes.initWithTypes({{ volume_types|safe|default:"{}" }});
    });
  }
</script>

platform2.orbit8.com/openstack-dashboard/openstack_dashboard/dashboards/project/volumes/templates/volumes/volumes/_retype.html
{% extends "horizon/common/_modal_form.html" %}
{% load i18n %}

{% block modal-body-right %}
  <h3>{% trans "Description:" %}</h3>
  <p>{% blocktrans %}
      Change the volume type of a volume after its creation.
      This is equivalent to the <tt>cinder retype</tt> command.
     {% endblocktrans %}
  </p>
  <p>{% blocktrans %}
      The "Volume Type" selected must be different from the current volume type.
     {% endblocktrans %}
  </p>
  <p>{% blocktrans %}
      The "Migration Policy" is only used if the volume retype cannot be
      completed. If the "Migration Policy" is "On Demand", the back end will
      perform volume migration. Note that migration may take a significant
      amount of time to complete, in some cases hours.
     {% endblocktrans %}
  </p>
{% endblock %}

platform2.orbit8.com/openstack-dashboard/openstack_dashboard/dashboards/project/volumes/templates/volumes/volumes/_upload_to_image.html
{% extends "horizon/common/_modal_form.html" %}
{% load i18n %}

{% block modal-body-right %}
  <h3>{% trans "Description:" %}</h3>
  <p>{% blocktrans %}
      Upload the volume to the Image Service as an image.
      This is equivalent to the <tt>cinder upload-to-image</tt> command.
     {% endblocktrans %}
  </p>
  <p>{% blocktrans %}
      Choose "Disk Format" for the image. The volume images are created with
      the QEMU disk image utility.
     {% endblocktrans %}
  </p>
  {% if volume.status == 'in-use' %}
    <p>{% blocktrans %}
        When the volume status is "in-use", you can use "Force" to upload the
        volume to an image.
       {% endblocktrans %}
    </p>
  {% endif %}
{% endblock %}